spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/elicefirstproject_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1715
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update